version: '2'
services:
    node-red:
        image: elzekool/rpi-nodered
        ports:
            - "1880:1880"
    mosquitto:
        image: pascaldevink/rpi-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
    gost-db:
        image: geodan/rpi-gost-db
        volumes:
            - /home/pi/.local/share/postgresql:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: gost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    gost:
        image: geodan/rpi-gost
        depends_on:
            - mosquitto
            - gost-db
        environment:
            GOST_DB_HOST: gost-db
            GOST_MQTT_HOST: mosquitto
    dashboard:
        image: geodan/rpi-gost-dashboard
        ports:
          - "8080:8080"
        depends_on:
            - gost
